name: Daily Insight Bot

on:
  schedule:
    # 00:30 UTC is 08:30 Malaysia Time (UTC+8)
    - cron: '30 0 * * *'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Daily Insight Report
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python daily_insight_app/run_once.py